CREATE DATABASE LAB_11_2
USE LAB_11_2
CREATE TABLE Class(
ClassCode varchar(10) PRIMARY KEY,
HeadTeacher varchar(30),
Room varchar(30),
TimeSlot char,
CloseDate datetime)
GO
CREATE TABLE Student(
RollNO varchar(10) PRIMARY KEY,
ClassCode varchar(10),
FullName varchar(30),
Male bit,
BirthDate datetime,
Address varchar(30),
Province char(20),
Email varchar(30),
CONSTRAINT fk1 FOREIGN KEY (ClassCode) REFERENCES Class(ClassCode))
GO
CREATE TABLE Subject(
SubjectCode varchar(10) PRIMARY KEY,
SubjectName varchar(40),
WMark bit,
PMark bit,
WTest_per int,
PTest_per int
)
GO
CREATE TABLE Mark(
RollNo varchar(10),
SubjectCode varchar(10),
WMark float,
PMark float,
Mark float,
CONSTRAINT pr1 PRIMARY KEY (RollNo, SubjectCode),
CONSTRAINT fk2 FOREIGN KEY (RollNO) REFERENCES Student(RollNo),
CONSTRAINT fk3 FOREIGN KEY (SubjectCode) REFERENCES Subject(SubjectCode))
GO

--1
CREATE TRIGGER BEFORE_SUBJECT_INSERT
ON Subject
FOR INSERT
AS
BEGIN
	IF EXISTS(SELECT SubjectName FROM inserted WHERE SubjectName IN (SELECT SubjectName FROM Subject))
	BEGIN
		PRINT 'TRUNG SUBJECT'
		ROLLBACK TRAN
	END
END
GO
--2
CREATE TRIGGER BEFORE_STUDENT_UPDATE
ON Student
FOR UPDATE
AS
BEGIN
	IF EXISTS(SELECT Province FROM inserted WHERE LEN(Province)!=2)
	BEGIN
	PRINT 'KHONG DUOC UPDATE'
	ROLLBACK TRAN
	END
END
GO
--3
CREATE TRIGGER BEFORE_CLASS_INSERT
ON Class
FOR INSERT
AS
BEGIN
	IF EXISTS (SELECT TimeSlot FROM inserted WHERE TimeSlot NOT LIKE '[GIML]')
		BEGIN
			PRINT 'Valid'
			ROLLBACK TRAN
		END
END
GO
--4
CREATE TRIGGER AFTER_SUBJECT_DELETE
ON SUBJECT
FOR DELETE
AS
DELETE FROM MARK WHERE SubjectCode IN (SELECT SubjectCode FROM DELETED)
GO
-- 5
CREATE TRIGGER BEFORE_AFTER_CLASS_DELETED
ON CLASS
FOR DELETE
AS
BEGIN 
	DELETE FROM STUDENT 
	WHERE CLASSCODE IN (SELECT ClassCode FROM DELETED)
	BEGIN 
		IF EXISTS ( SELECT * FROM MARK WHERE RollNo IN ( SELECT RollNo FROM Student WHERE CLASSCODE IN (SELECT ClassCode FROM DELETED)))
		BEGIN
		PRINT 'DO NOT ALLOWED TO DELETE CLASS WHEN MARK IS EXISTS'
		ROLLBACK TRAN
		END
	END
END
GO
--6
CREATE TRIGGER BEFORE_SUBJECT_DELETE
ON SUBJECT
FOR DELETE
AS
BEGIN
	DECLARE @COUNT INT
	SELECT @COUNT = COUNT(ROLLNO) FROM MARK WHERE SubjectCode IN ( SELECT SubjectCode FROM DELETED)
	BEGIN
		IF @COUNT > 5
		BEGIN
			PRINT 'SO HOC SINH DANG KI LON HON 5. KHONG DUOC XOA SUBJECT'
			ROLLBACK TRAN
		END
		IF @COUNT <=5 
		BEGIN 
			IF EXISTS (SELECT * FROM Mark WHERE SubjectCode IN (SELECT SubjectCode FROM DELETED))
			BEGIN
				PRINT' CHUA XOA MARK CUA SUBJECT'
				ROLLBACK TRAN
			END
		END
	END
END